name = "mawridreader-nextgen"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MAWRID_BUCKET"
bucket_name = "mawrid-dictionaries"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"